version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step1
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: start_server.sh # 경로 주의 (artifacts에서 경로 무시했으므로)
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: stop_server.sh
      timeout: 60
      runas: ec2-user